export const STATS_MAP = {
  accurateLongBalls: 'Accurate Long Ball',
  accuratePasses: 'Accurate Pass',
  assists: 'Assists',
  bigChancesCreated: 'Big Chances Created',
  bigChancesMissed: 'Bug Chances Missed',
  cleanSheet: 'Clean Sheet',
  clearances: 'Clearances',
  expectedAssists: 'Expected Assists',
  expectedGoals: 'Expected Goals',
  freeKickGoal: 'Free Kick Goals',
  goals: 'Goals',
  goalsAssistsSum: 'Goals Assists Sum',
  goalsPrevented: 'Goals Prevented',
  interceptions: 'Interceptions',
  keyPasses: 'Key Passes',
  leastConceded: 'Least Conceded',
  mostConceded: 'Most Conceded',
  penaltyGoals: 'Penalty Goals',
  penaltyWon: 'Penalty Won',
  possessionLost: 'Possession Lost',
  rating: 'Rating',
  redCards: 'Red Cards',
  saves: 'Saves',
  scoringFrequency: 'Scoring Frequency',
  shotsOnTarget: 'Shots on Target',
  successfulDribbles: 'Successful Dribbles',
  tackles: 'Tackles',
  totalShots: 'Total Shots',
  yellowCards: 'Yellow Cards',
}
